name: Wikyta
favicon: null
layout_spectrum: 0.37288
typography_spectrum: 0.4223646796308458
title: Marketing en Internet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#20201e'
    - '#7a9900'
    - '#cccbc7'
    - '#aa3f3c'
  brandStrength: 0.875
  lightness: 0.9224324396345764
  saturation: 0.125
  rhythmicContrast: 0.89366291067563
purpose: []
